repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: trailing-whitespace
        exclude: .snap
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies:
          - dlint
          - flake8-bugbar
          - flake8-implicit-str-concat
          - flake8-absolute-import
          - flake8-black
          - flake8-docstrings
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      - id: shellcheck
        args: [ "--exclude=SC2230,SC1117,SC2015,SC2059" ]
        additional_dependencies: [ ]
